import type { Metadata } from "next";
import Link from "next/link";
import ContentPage from "@/components/ContentPage";
import SupportPanel from "@/components/SupportPanel";

export const metadata: Metadata = {
  title: "Support the site — what it costs and who has given",
  description:
    "What DebtRunway costs to run, every taka received and every taka spent, and how to give through bKash if the site has been useful to you.",
  alternates: { canonical: "/support" },
  // A ledger is only current at the moment it is read, and a cached copy of a
  // donation total is a wrong donation total.
  robots: { index: true, follow: true },
};

export default function Page() {
  return (
    <ContentPage
      heading="Support"
      intro="What this costs, where every taka has gone, and how to help if it has been useful to you. Nothing here is behind a payment and nothing will be."
    >
      <SupportPanel />

      <div className="mt-12 border-t border-line pt-8">
        <h2 className="rule-gold display text-2xl">Why a ledger at all</h2>
        <p className="mt-4 leading-relaxed">
          Because asking for money without showing what happens to it is how
          trust gets spent. If someone gives ৳500 towards a scholar&rsquo;s
          review of the inheritance engine, they should be able to come back in
          six months and see either that the review happened or that the money
          is still sitting there waiting.
        </p>
        <p className="mt-3 leading-relaxed">
          The figures above are not generated by the form. They are written
          into the site&rsquo;s source by hand, after each transaction has been
          matched against the account, and the change is{" "}
          <Link
            href="/about"
            className="font-medium text-brand underline decoration-brand/30 underline-offset-2 transition hover:decoration-brand"
          >
            recorded publicly
          </Link>{" "}
          like every other change to this site. That is slower than a live
          counter. It is also the only version that cannot be filled in by a
          stranger with an imaginary transaction ID.
        </p>

        <h2 className="rule-gold display mt-10 text-2xl">
          What giving does not buy
        </h2>
        <p className="mt-4 leading-relaxed">
          Nothing. There is no members&rsquo; area, no removed advertising for
          donors, no calculator that runs differently for someone who has
          given, and no plan to add any of those. Every page works the same for
          everyone who opens it, and a reader who never gives anything is using
          the site exactly as intended.
        </p>
        <p className="mt-3 leading-relaxed">
          Giving quietly is better than giving publicly. The list exists so the
          spending can be audited, not so anyone can be seen doing it — leave
          the name field blank and the entry reads Anonymous, and it counts
          towards the total exactly the same.
        </p>
      </div>
    </ContentPage>
  );
}
